import React from 'react';

export const Lorem = () => (
  <>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat cum repellat voluptate molestias aut pariatur
    corrupti facere quas eaque, aliquid fuga, deserunt similique officia ipsa! Cum esse laudantium eligendi commodi?
  </>
);
